### ISSUE TITLE
Make the extension work on macOS and Windows

### ISSUE THREAD

**Issue by alexarchambault** [laughedelic/coursier-setup#2]
Really great to have such an extension, thanks for it @laughedelic!

FYI, I wrote [this script](https://github.com/coursier/ci-scripts/blob/master/setup.sh) some time ago (but didn't talk about it much at the time). It allows to get the coursier CLI for Linux / macOS / Windows, and also downloads it via the coursier cache, so that if [cache-action](https://github.com/coursier/cache-action) runs before, nothing needs to be downloaded once the launcher is in cache. It also allows one to specify the coursier CLI version upfront (but needs to be updated when new coursier versions are tagged…).

You may want to embed that script in the action here, to have this extension work on macOS and Windows too, and use the cache. One point to pay attention to though, is that the coursier version it uses needs to be part of the cache key of [cache-action](https://github.com/coursier/cache-action). (Else the cache may not be saved after bumping the coursier version.)

It might be possible to pass parameters to [cache-action](https://github.com/coursier/cache-action) from this action, I'm not sure… That said, it's not that big a deal if the CLI is not cached, as it's downloaded straight from GitHub…

**Comment by laughedelic** [comment]
Hi @alexarchambault! Thanks for the feedback and the hints!

I will take a look at the script. Sure, I want to make it work on any of the available platforms. Current implementation is just a start 🙂

**Comment by laughedelic** [comment]
This got closed by accident.

**Comment by laughedelic** [comment]
Now this is fixed: https://github.com/laughedelic/coursier-setup/actions/runs/355006200
